[bg]
Bytes = '''$1 байта'''
KB = '''$1 KB'''
MB = '''$1 MB'''
about = '''Относно'''
about_alpha_intro = '''Това е завършена версия'''
about_beta_intro = '''Това е тестова версия'''
about_qr = '''Файлът е генериран'''
about_vdh = '''Относно Video DownloadHelper'''
action_abort_description = '''Прекъсни изпълняваната задача'''
action_abort_title = '''Прекъсни'''
action_as_default = '''Използвайте това действие по подразбиране.'''
action_blacklist_description = '''Клипове с произход/обслужвани от избраните домейни ще бъдат игнорирани'''
action_blacklist_title = '''Добави в черния списък'''
action_copyurl_description = '''Копирай адреса до медията в клипборда'''
action_copyurl_title = '''Копирай URL'''
action_deletehit_description = '''Изтрий попаденията от текущия списък'''
action_deletehit_title = '''Изтрий'''
action_details_description = '''Покажи детайли за попадението'''
action_details_title = '''Детайли'''
action_download_description = '''Сваляне на файла на твърдия диск'''
action_download_title = '''Сваляне'''
action_downloadconvert_description = '''Свали медията и я конвертирай до друг формат'''
action_downloadconvert_title = '''Свали и конвертирай'''
action_openlocalfile_description = '''Отвори текущия медия файл'''
action_openlocalfile_title = '''Отвори медията'''
action_pin_description = '''Направи попаденията постоянни'''
action_pin_title = '''Закачи'''
action_quickdownload_description = '''Сваляне без питане за дестинацията'''
action_quickdownload_title = '''Бързо сваляне'''
adaptative = '''Адаптивно $1'''
add_to_blacklist = '''Добави в черния списък'''
add_to_blacklist_help = '''Клипове с произход/обслужвани от избраните домейни ще бъдат игнорирани'''
advanced = '''Допълнително'''
aggregating = '''Струпване...'''
analyze_page = '''Анализирай страницата'''
appDesc = '''Download Videos from the Web'''
appName = '''Video DownloadHelper'''
appearance = '''Изглед'''
audio_only = '''Само аудио.'''
behavior = '''Поведение'''
blacklist = '''Черен списък'''
cancel = '''Отказ'''
chrome_install_firefox = '''Инсталирайте Firefox'''
chrome_install_fx_vdh = '''Video DownloadHelper за Firefox'''
chrome_noyt_text = '''За съжаление Chrome Web Store не позволява разширения за сваляне на YouTube видео, така че се наложи да премахнем тази опция.'''
chrome_noyt_text2 = '''Може да ползвате Video DownloadHelper за сваляне на YouTube видео във Firefox версията.'''
chrome_warning_yt = '''Предупреждение при Chrome разширения и YouTube'''
clear_hits = '''Изчисти попаденията'''
congratulations = '''Поздравления!'''
continue = '''Продължи'''
convconf_2passes = '''2 паса'''
convconf_ac = '''Аудио канали'''
convconf_acnone = '''Нищо'''
convconf_acodec = '''Аудио кодек'''
convconf_aspect = '''Пропорции'''
convconf_audiobitrate = '''Аудио битрейт'''
convconf_audiofreq = '''Аудио честота'''
convconf_audioonly = '''Само аудио'''
convconf_bitrate = '''Битрейт'''
convconf_container = '''Формат'''
convconf_duplicate = '''Дублиране'''
convconf_ext = '''Изходно файлово разширение'''
convconf_extra = '''Допълнителни параметри'''
convconf_level = '''Ниво'''
convconf_mono = '''Моно'''
convconf_new = '''Нов'''
convconf_preset = '''Настройки'''
convconf_profilev = '''Видео профил'''
convconf_rate = '''Кадъра в секунда'''
convconf_readonly = '''настройката по подразбиране е само за четене. Копирайте, за да модифицирате.'''
convconf_remove = '''Премахни'''
convconf_reset = '''Възстанови всичко'''
convconf_reset_confirm = '''Това ще премахне всичките Ви потребителски настройки'''
convconf_save = '''Запиши'''
convconf_size = '''Размер на кадъра'''
convconf_stereo = '''Стерео'''
convconf_target = '''Цел'''
convconf_tune = '''Мелодия'''
convconf_vcodec = '''Видео кодек'''
convconf_videobitrate = '''Видео битрейт'''
conversion_outputs = '''Изходна папка за конвертираното'''
convert = '''Конвертирай'''
convert_local_files = '''Конвертирай наличните файлове'''
converter_needed_aggregate = '''Тази операция се нуждае от конверто инсталиран на Вашата система за прихващане на видео и аудио стрийм'''
converter_needed_aggregate_why = '''Защо имам нужда от конвертор?'''
converter_needs_reg = '''Нужна е регистрация.'''
converter_reg_audio = '''You requested, either explicitely or from an automatic conversion rule, the generation of an audio-only media file. This requires a registered converter.'''
converting = '''Конвертиране...'''
convrule_convert = '''Конвертирай'''
convrule_domain = '''Домейн'''
convrule_extension = '''Разширение'''
copy_of = '''Копиране на $1'''
custom_output = '''Потребителски изходен формат'''
details_parenthesis = '''(Детайли)'''
dlconv_download_and_convert = '''Свали и конвертирай'''
dlconv_output_details = '''Настройване на изходните детайли'''
donate = '''Дарение'''
donate_vdh = '''Video DownloadHelper помощ'''
downloading = '''Сваляне...'''
errors = '''Грешки'''
explain_qr1 = '''Ще забележите, че видеото съдържа воден знак в ъгъла'''
explain_qr2 = '''Това е защото сте ползвали ADP  вариант и конвертирането не е било регистрирано'''
failed_aggregating = '''Провалено струпване "$1"'''
failed_converting = '''Провалено конвертиране "$1"'''
failed_getting_info = '''Провалено извличане на данни от "$1"'''
file_dialog_name = '''Име'''
file_generated = '''Файлът "$1" беше генериран'''
file_ready = '''"$1" е вече готов'''
from_domain = '''От $1'''
gallery = '''Галерия'''
gallery_files_types = '''$1 файлове'''
gallery_from_domain = '''Галерия от $1'''
gallery_links_from_domain = '''Линкове от $1'''
general = '''Основно'''
get_conversion_license = '''Вземете регистрация за конвертирането'''
hit_details = '''Детайли на попадението.'''
hit_go_to_tab = '''Отидете в таб'''
in_current_tab = '''В текущия таб'''
in_other_tab = '''В други табове'''
license_key = '''Лицензен ключ'''
logs = '''Логове'''
media = '''Медия'''
more = '''Повече...'''
no_media_to_process = '''Няма медия за обработка'''
not_again_3months = '''Не ме безпокойте с това в близките 3 месеца'''
not_see_again = '''Не извеждай това съобщение повторно'''
number_type = '''$1 $2'''
orphan = '''Орфан'''
pinned = '''Фиксирани'''
quality_medium = '''Средно'''
quality_small = '''ниско'''
queued = '''На опашката...'''
register_converter = '''Register converter'''
register_existing_license = '''Регистрирайте съществуващ лиценз'''
registered_email = '''E-mail'''
registered_key = '''Ключ'''
req_donate = '''Бихте ли подкрепили разработването като направите дарение?'''
req_review = '''Евентуално, имате ли нещо против да напишете добър отзвук в сайта на Mozilla addon?'''
req_review_link = '''Напишете ревю за Video DownloadHelper'''
running = '''Стартирани'''
save = '''Запиши'''
select_files_to_convert = '''Конвертирай наличните файлове'''
settings = '''Настройки'''
smartnamer_delay = '''Забавяне именоването на прихванатото (ms)'''
smartnamer_domain = '''Домейн'''
smartnamer_get_name_from_header_url = '''Вземи име от хедъра или URL адрес'''
smartnamer_get_name_from_page_content = '''Вземи име от съдържанието на страницата'''
smartnamer_get_name_from_page_title = '''Вземи име от заглавието на страницата'''
smartnamer_get_obfuscated_name = '''Използвай завоалирано име'''
smartnamer_regexp = '''Нормален изглед'''
smartnamer_selected_text = '''Селектиран текст'''
smartnamer_xpath_expr = '''XPath изглед'''
supported_sites = '''Поддържани сайтове'''
tell_me_more = '''Кажете ми повече за това'''
title = '''Video DownloadHelper'''
validate_license = '''Регистрационен лиценз'''
variants_list_adp = '''Адаптивни варианти'''
variants_list_full = '''Варианти'''
vdh_notification = '''Video DownloadHelper'''
version = '''Версия $1'''
video_only = '''Само видео.'''
video_qualities = '''Видео качества'''
weh_prefs_description_autoPin = '''Закачи попаденията след сваляне'''
weh_prefs_description_blacklistEnabled = '''Предотврати някой сайтове да активират разпознаването на медия'''
weh_prefs_description_converterAggregTuneH264 = '''Принудително H264 струпване'''
weh_prefs_description_downloadControlledMax = '''Контролиране броя на едновременно сваляните файлове, за поддържане на свободен капацитет.'''
weh_prefs_description_mediaweightMinSize = '''Пренебрегни попадения под указания размер'''
weh_prefs_description_mediaweightThreshold = '''Принудително засичане на по-малък размер'''
weh_prefs_description_networkFilterOut = '''Обичаен изглед с игнориране на някой медия адреси'''
weh_prefs_description_noPrivateNotification = '''Без известия за лични попадения'''
weh_prefs_description_notifyReady = '''Извести, когато обработиш'''
weh_prefs_description_orphanExpiration = '''Изтичане на времето в секунди преди премахването на орфановите попадения'''
weh_prefs_description_qualitiesMaxVariants = '''Максимален брой на показани варианти за едно и също време'''
weh_prefs_description_smartnamerFnameMaxlen = '''Осигуряване генерираните имена на файлове да не надвишават този размер'''
weh_prefs_iconActivation_option_anytab = '''Попадения от всеки таб'''
weh_prefs_iconActivation_option_currenttab = '''Попадение от текущия таб'''
weh_prefs_iconBadge_option_activetab = '''Медия от активния таб'''
weh_prefs_iconBadge_option_anytab = '''Медия от всеки таб'''
weh_prefs_iconBadge_option_mixed = '''Смесено'''
weh_prefs_iconBadge_option_none = '''Няма'''
weh_prefs_iconBadge_option_pinned = '''Pinned hits'''
weh_prefs_iconBadge_option_tasks = '''Стартирани задачи'''
weh_prefs_label_autoPin = '''Автоматично закачане'''
weh_prefs_label_blacklistEnabled = '''Активирай черния списък'''
weh_prefs_label_converterThreads = '''Бройки за конвертиране'''
weh_prefs_label_downloadControlledMax = '''Максимално текущи сваляния'''
weh_prefs_label_hitsGotoTab = '''Покажи бутон за отваряне в таб'''
weh_prefs_label_iconActivation = '''Активиране на иконите'''
weh_prefs_label_iconBadge = '''Надпис на иконата'''
weh_prefs_label_ignoreProtectedVariants = '''Игнорирай защитените варианти'''
weh_prefs_label_mediaExtensions = '''Засечи разширенията'''
weh_prefs_label_medialinkMinImgSize = '''Минимален размер за изображение'''
weh_prefs_label_medialinkScanImages = '''Засечи вградените изображения'''
weh_prefs_label_medialinkScanLinks = '''Засечи линковете до медия'''
weh_prefs_label_mediaweightMinSize = '''Минимален размер'''
weh_prefs_label_mediaweightThreshold = '''Праг на размера'''
weh_prefs_label_networkFilterOut = '''Мрежови филтър'''
weh_prefs_label_networkProbe = '''Мрежово проучване'''
weh_prefs_label_orphanExpiration = '''Орфаново изтичане на времето'''
weh_prefs_label_qualitiesMaxVariants = '''Максимални варианти'''
weh_prefs_label_smartnamerFnameMaxlen = '''Максимална дължина на файлово име'''
weh_prefs_label_smartnamerFnameSpaces = '''Главен панел за дълги заглавия'''
weh_prefs_label_titleMode = '''Главен панел за дълги заглавия'''
weh_prefs_smartnamerFnameSpaces_option_hyphen = '''Замести с тирета'''
weh_prefs_smartnamerFnameSpaces_option_keep = '''Запази'''
weh_prefs_smartnamerFnameSpaces_option_remove = '''Премахни'''
weh_prefs_smartnamerFnameSpaces_option_underscore = '''Замести с долни черти'''
weh_prefs_titleMode_option_left = '''Многоточие отляво'''
weh_prefs_titleMode_option_multiline = '''През няколко реда'''
weh_prefs_titleMode_option_right = '''Многоточие отдясно'''
you_downloaded_n_videos = '''току що успешно свалихте Вашия $1th файл с Video DownloadHelper.'''
