[is]
Bytes = "$1 bæti"
KB = "$1 KB"
MB = "$1 MB"
about = "Um hugbúnaðinn"
about_alpha_intro = "Þetta er alfa-útgáfa."
about_beta_intro = "Þetta er beta-útgáfa."
about_qr = "Skrá útbúin"
about_vdh = "Um Video DownloadHelper niðurhalshjálpina"
action_abort_description = "Hætta við aðgerðina sem er í gangi"
action_abort_title = "Hætta við"
action_as_default = "Nota sjálfgefið þessa aðgerð"
action_avplay_description = "Spila myndskeiðið í innbyggðum skoðara umbreytiforritsins"
action_avplay_title = "Afspilun"
action_blacklist_description = "Myndskeið sem koma frá eða er miðlað af völdum lénum verða hunsuð"
action_blacklist_title = "Bæta á bannlista"
action_copyurl_description = "Afrita slóð margmiðlunargagnanna á klippispjaldið"
action_copyurl_title = "Afrita slóð"
action_deletehit_description = "Eyða samsvörun af núverandi lista"
action_deletehit_title = "Eyða"
action_details_description = "Birta nánari upplýsingar um samsvörunina"
action_details_title = "Nánar"
action_download_description = "Sækja og vista skrána á harða diskinn þinn"
action_download_title = "Niðurhal"
action_downloadconvert_description = "Sækja margmiðlunargögn og umbreyta á annað snið"
action_downloadconvert_title = "Sækja og umbreyta"
action_openlocalfile_description = "Opna margmiðlunargögn af þessari tölvu"
action_openlocalfile_title = "Opna margmiðlunargögn"
action_pin_description = "Gera samsvörun fasta"
action_pin_title = "Festa"
action_quickdownload_description = "Sækja án þess að spyrja um úttaksmöppu"
action_quickdownload_title = "Skyndiniðurhal"
adaptative = "Aðlaganlegt $1"
add_to_blacklist = "Bæta á bannlista"
add_to_blacklist_help = "Myndskeið sem koma frá eða er miðlað af völdum lénum verða hunsuð"
advanced = "Nánar"
aggregating = "Safna saman..."
analyze_page = "Greina síðu"
appDesc = "Download Videos from the Web"
appName = "Video DownloadHelper"
appearance = "Útlit"
audio_only = "Einungis hljóð"
behavior = "Hegðun"
blacklist = "Bannlisti"
cancel = "Hætta við"
chrome_install_firefox = "Setja upp Firefox"
chrome_install_fx_vdh = "Video DownloadHelper fyrir Firefox"
chrome_noyt_text = "Því miður, leyfir Chrome Web Store ekki viðbætur sem sækja YouTube-myndskeið, þannig að við þurftum að fjarlægja þennan eiginleika."
chrome_noyt_text2 = "Þú getur notað VDH-niðurhalshjálpina til að sækja YouTube-myndskeið með Firefox-útgáfunni."
chrome_warning_yt = "Aðvörun vegna Chrome-viðbóta og YouTube"
clear_hits = "Hreinsa samsvaranir"
clear_logs = "Hreinsa annála"
congratulations = "Til hamingju!"
continue = "Halda áfram"
convconf_2passes = "2 umferðir"
convconf_ac = "Hljóðrásir"
convconf_acnone = "Ekkert"
convconf_acodec = "Hljóðkóðunarlykill"
convconf_aspect = "Stærðarhlutföll"
convconf_audiobitrate = "Hljóð-bitahraði:"
convconf_audiofreq = "Hljóðtíðni"
convconf_audioonly = "Einungis hljóð"
convconf_bitrate = "Bitahraði"
convconf_container = "Skráasnið"
convconf_duplicate = "Tvítaka"
convconf_ext = "Skráarending frálagsskrár"
convconf_extra = "Aukabreytur"
convconf_level = "Stig"
convconf_mono = "Einóma"
convconf_new = "Nýtt"
convconf_preset = "Forstilling"
convconf_profilev = "Sniðskrá myndskeiðs"
convconf_rate = "Rammatíðni"
convconf_readonly = "Sjálfgefna uppsetningin er skrifvarin. Gerðu afrit af henni til að gera breytingar."
convconf_remove = "Fjarlægja"
convconf_reset = "Frumstilla allt"
convconf_reset_confirm = "Þetta mun fjarlægja allar sérsniðnar uppsetningar þínar"
convconf_save = "Vista"
convconf_size = "Rammastærð"
convconf_stereo = "Víðóma"
convconf_target = "Útkoma"
convconf_tune = "Fínstilling"
convconf_vcodec = "Myndkóðunarlykill"
convconf_videobitrate = "Bitahraði myndmerkis"
conversion_outputs = "Frálög umbreytinga"
convert = "Umbreyta"
convert_local_files = "Umbreyta staðværum skrám"
converter_needed_aggregate = "Þessi aðgerð krefst þess að umbreytiforrit sé uppsett á kerfinu þínu til að setja saman hljóð- og myndstreymi."
converter_needed_aggregate_why = "Hvers vegna þarf ég umbreytiforrit ?"
converter_needs_reg = "Skráningar er krafist"
converter_reg_audio = "Þú baðst, annað hvort sérstaklega eða með reglum fyrir sjálfvirka umbreytingu, um að útbúin væri margmiðlunarskrá sem inniheldur eingöngu hljóð. Þetta krefst skráðs umbreytiforrits."
converting = "Umbreyti..."
convrule_convert = "Umbreyta"
convrule_domain = "Lén"
convrule_extension = "Skráarending"
copy_of = "Afrit af $1"
custom_output = "Sérsniðin úttakssnið"
dash_streaming = "DASH streymi"
details_parenthesis = "(nánar)"
dlconv_download_and_convert = "Sækja og umbreyta"
dlconv_output_details = "Stilla frálag nánar"
donate = "Styrkja"
donate_vdh = "Hjálpa Video DownloadHelper"
downloading = "Sæki..."
errors = "Villur"
explain_qr1 = "Þú munt taka eftir því að myndskeiðið mun innifela vatnsmerki í horninu."
explain_qr2 = "Þetta er af því þú valdir ADP-tilbrigði og umbreytingarforritið hefur ekki verið skráð."
failed_aggregating = "Mistókst að safna saman \"$1\""
failed_converting = "Mistókst að umbreyta \"$1\""
failed_getting_info = "Mistókst að ná í upplýsingar frá \"$1\""
file_dialog_name = "Heiti"
file_generated = "Skráin \"$1\" hefur verið útbúin."
file_ready = "\"$1\" er núna tilbúið"
finalizing = "Geng frá..."
from_domain = "Frá $1"
gallery = "Myndasafn"
gallery_files_types = "$1 skrár"
gallery_from_domain = "Myndasafn frá $1"
gallery_links_from_domain = "Tenglar frá $1"
general = "Almennt"
get_conversion_license = "Fáðu notkunarleyfi fyrir umbreytiforrit"
hit_details = "Nánar um samsvörun"
hit_go_to_tab = "Fara á flipa"
hls_streaming = "HLS streymi"
in_current_tab = "Á þessum flipa"
in_other_tab = "Í öðrum flipum"
license_key = "Lykill notkunarleyfis"
logs = "Annálar"
media = "Margmiðlunargögn"
more = "Meira..."
no_media_current_tab = "Engin margmiðlunargögn til að vinna með í núverandi flipa"
no_media_to_process = "Engin margmiðlunargögn til að vinna með"
no_media_to_process_descr = "Smelltu á afspilun á myndskeiði til að hjálpa við að finna skrár…"
not_again_3months = "Ekki ónáða mig aftur með þetta næstu 3 mánuðina"
not_see_again = "Ekki sýna þessi skilaboð aftur"
number_type = "$1 $2"
orphan = "Einstæðingar"
pinned = "Fest"
quality_medium = "Miðlungs"
quality_small = "Lág"
queued = "Í biðröð..."
register_converter = "Skrá umbreytiforrit"
register_existing_license = "Skrá notkunarleyfi sem þegar er til staðar"
registered_email = "Tölvupóstfang"
registered_key = "Lykill"
req_donate = "Myndirðu íhuga að styðja við verkefnið og gefa einhverja smáupphæð ?"
req_review = "Nú, eða kannski skrifa skemmtilega umsögn á vefsvæðinu fyrir Mozilla viðbæturnar ?"
req_review_link = "Skrifa umsögn um VDH-niðurhalshjálpina"
running = "Í gangi"
save = "Vista"
select_files_to_convert = "Umbreyta staðværum skrám"
settings = "Stillingar"
smartnamer_delay = "Töf á nafnagripi (msek)"
smartnamer_domain = "Lén"
smartnamer_get_name_from_header_url = "Ná í heiti úr haus skjals/URL-slóð"
smartnamer_get_name_from_page_content = "Ná í heiti úr innihaldi síðu"
smartnamer_get_name_from_page_title = "Ná í heiti úr titli síðu"
smartnamer_get_obfuscated_name = "Nota óskírt heiti"
smartnamer_regexp = "Regluleg segð"
smartnamer_selected_text = "Valinn texti"
smartnamer_xpath_expr = "XPath-segð"
supported_sites = "Studd vefsvæði"
tell_me_more = "Segðu mér meira um þetta"
title = "Video DownloadHelper"
validate_license = "Skrá notkunarleyfi"
variants_list_adp = "Aðlaganleg tilbrigði (ADP)"
variants_list_full = "Tilbrigði"
vdh_notification = "Video DownloadHelper"
version = "Útgáfa $1"
video_only = "Einungis myndskeið"
video_qualities = "Gæði myndskeiða"
weh_prefs_dashOnAdp_option_audio = "Sækja hljóðskrá"
weh_prefs_dashOnAdp_option_audio_video = "Safna saman hljóði og myndskeiði"
weh_prefs_dashOnAdp_option_video = "Sækja myndskeið"
weh_prefs_description_adpHide = "Ekki birta ADP-tilbrigði í niðurhalslista"
weh_prefs_description_autoPin = "Festa samsvörun eftir niðurhal."
weh_prefs_description_blacklistEnabled = "Koma í veg fyrir að sum vefsvæði virkji greiningu á margmiðlunargögnum."
weh_prefs_description_chunksEnabled = "Streymi í knippum virkt"
weh_prefs_description_converterAggregTuneH264 = "Þvinga fínstillingu H264 við samsöfnun"
weh_prefs_description_dashHideM4s = "Ekki birta .m4s færslur í niðurhalslista"
weh_prefs_description_dashOnAdp = "Þegar DASH inniheldur bæði hljóð og myndskeið"
weh_prefs_description_downloadControlledMax = "Stýrir fjölda þeirra niðurhala sem viðbótin útbýr og keyrir samhliða, til að spara bandbreidd."
weh_prefs_description_downloadRetries = "Fjöldi tilrauna við niðurhal"
weh_prefs_description_downloadRetryDelay = "Tími sem líður milli endurtekinna tilrauna til niðurhals (ms)"
weh_prefs_description_hlsDownloadAsM2ts = "Sækja HLS streymi sem M2TS"
weh_prefs_description_mediaweightMinSize = "Hunsa samsvaranir undir þessari stærð."
weh_prefs_description_mediaweightThreshold = "Þvinga fram leit að skrám sem eru stærri en þetta."
weh_prefs_description_mpegtsHideTs = "Ekki birta .ts færslur í niðurhalslista"
weh_prefs_description_networkFilterOut = "Regluleg segð sem hunsar ákveðnar slóðir á margmiðlunargögn."
weh_prefs_description_noPrivateNotification = "Engar tilkynningar fyrir einkasamsvaranir"
weh_prefs_description_notifyReady = "Láta vita þegar vinnslu lýkur"
weh_prefs_description_orphanExpiration = "Biðtími í sekúndum áður en stakar samsvaranir eru fjarlægðar."
weh_prefs_description_qualitiesMaxVariants = "Hámarksfjöldi tilbrigða sem sýndar eru fyrir eitt og sama myndskeiðið."
weh_prefs_description_smartnamerFnameMaxlen = "Tryggir að útbúin skráaheiti fari ekki yfir þessa lengd."
weh_prefs_iconActivation_option_anytab = "Samsvörun af hvaða flipa sem er"
weh_prefs_iconActivation_option_currenttab = "Samsvörun af þessum flipa"
weh_prefs_iconBadge_option_activetab = "Margmiðlunargögn af virkum flipa"
weh_prefs_iconBadge_option_anytab = "Margmiðlunargögn af hvaða flipa sem er"
weh_prefs_iconBadge_option_mixed = "Blandað"
weh_prefs_iconBadge_option_none = "Ekkert"
weh_prefs_iconBadge_option_pinned = "Festar samsvaranir"
weh_prefs_iconBadge_option_tasks = "Keyrandi verk"
weh_prefs_label_autoPin = "Sjálfvirk festing"
weh_prefs_label_avplayEnabled = "Spilari virkur"
weh_prefs_label_blacklistEnabled = "Virkja bannlista"
weh_prefs_label_chunksConcurrentDownloads = "Samtímis niðurhöluð knippi"
weh_prefs_label_chunksEnabled = "Streymi í knippum (chunked)"
weh_prefs_label_chunksPrefetchCount = "Fjöldi forsóttra knippa"
weh_prefs_label_converterThreads = "Umbreytingarþræðir"
weh_prefs_label_dashEnabled = "DASH virkt"
weh_prefs_label_downloadControlledMax = "Hámarksfjöldi samtímis niðurhala"
weh_prefs_label_hitsGotoTab = "Birta Fara-á-flipa haldfang"
weh_prefs_label_hlsEnabled = "HLS virkt"
weh_prefs_label_iconActivation = "Virkjun táknmyndar"
weh_prefs_label_iconBadge = "Bakgrunnur táknmynda"
weh_prefs_label_ignoreProtectedVariants = "Hunsa varin tilbrigði"
weh_prefs_label_mediaExtensions = "Skynja skráarendingar"
weh_prefs_label_medialinkMinImgSize = "Lágmarksstærð mynda"
weh_prefs_label_medialinkScanImages = "Finna ígræddar myndir"
weh_prefs_label_medialinkScanLinks = "Finna tengla á margmiðlunargögn"
weh_prefs_label_mediaweightMinSize = "Lágmarksstærð"
weh_prefs_label_mediaweightThreshold = "Stærðarmörk"
weh_prefs_label_networkFilterOut = "Netkerfissía út"
weh_prefs_label_networkProbe = "Skönnun netkerfis"
weh_prefs_label_orphanExpiration = "Tímamörk gildistíma einstæðinga"
weh_prefs_label_qualitiesMaxVariants = "Hámarksfjöldi tilbrigða"
weh_prefs_label_smartnamerFnameMaxlen = "Hámarkslengd skráaheita"
weh_prefs_label_smartnamerFnameSpaces = "Langir titlar á aðalspjaldi"
weh_prefs_label_titleMode = "Langir titlar á aðalspjaldi"
weh_prefs_smartnamerFnameSpaces_option_hyphen = "Skipta út fyrir bandstrik"
weh_prefs_smartnamerFnameSpaces_option_keep = "Halda"
weh_prefs_smartnamerFnameSpaces_option_remove = "Fjarlægja"
weh_prefs_smartnamerFnameSpaces_option_underscore = "Skipta út fyrir lágstrik"
weh_prefs_titleMode_option_left = "Úrfellingarmerki til vinstri"
weh_prefs_titleMode_option_multiline = "Yfir margar línur"
weh_prefs_titleMode_option_right = "Úrfellingarmerki til hægri"
you_downloaded_n_videos = "Þú varst að sækja skrá númer $1th með VDH-niðurhalshjálpinni."
v9_no_media_current_tab = "Engin margmiðlunargögn til að vinna með í núverandi flipa"
v9_no_media_to_process_descr = "Smelltu á afspilun á myndskeiði til að hjálpa við að finna skrár…"
v9_converter_needs_reg = "Skráningar er krafist"
v9_get_conversion_license = "Fáðu notkunarleyfi fyrir umbreytiforrit"
v9_converter_reg_audio = "Þú baðst, annað hvort sérstaklega eða með reglum fyrir sjálfvirka umbreytingu, um að útbúin væri margmiðlunarskrá sem inniheldur eingöngu hljóð. Þetta krefst skráðs umbreytiforrits."
v9_chrome_warning_yt = "Aðvörun vegna Chrome-viðbóta og YouTube"
v9_chrome_noyt_text2 = "Þú getur notað VDH-niðurhalshjálpina til að sækja YouTube-myndskeið með Firefox-útgáfunni."
v9_about_qr = "Skrá útbúin"
v9_explain_qr1 = "Þú munt taka eftir því að myndskeiðið mun innifela vatnsmerki í horninu."
v9_not_see_again = "Ekki sýna þessi skilaboð aftur"
v9_tell_me_more = "Segðu mér meira um þetta"
v9_settings = "Stillingar"
v9_weh_prefs_label_downloadControlledMax = "Hámarksfjöldi samtímis niðurhala"
v9_vdh_notification = "Video DownloadHelper"
v9_file_ready = "\"$1\" er núna tilbúið"
