
[ko]
Bytes = '''$1바이트'''
GB = '''$1GB'''
KB = '''$1KB'''
MB = '''$1MB'''
about = '''정보'''
about_alpha_intro = '''현재 알파 버전입니다.'''
about_beta_intro = '''현재 베타 버전입니다.'''
about_chrome_licenses = '''크롬 라이센스에 대하여'''
about_qr = '''파일 생성됨'''
about_vdh = '''Video DownloadHelper 정보'''
action_abort_description = '''진행중인 작업 중단'''
action_abort_title = '''중단'''
action_as_default = '''이 작업을 기본값으로 사용'''
action_avplay_description = '''변환기 자체 뷰어로 비디오 재생'''
action_avplay_title = '''재생'''
action_blacklist_description = '''선택된 도메인에서 제공하는 비디오는 무시됩니다.'''
action_blacklist_title = '''차단 목록에 추가'''
action_bulkdownload_description = '''선택한 비디오 다운로드'''
action_bulkdownload_title = '''벌크 다운로드'''
action_bulkdownloadconvert_description = '''벌크 다운로드 후 선택 동영상 변환'''
action_bulkdownloadconvert_title = '''벌크 다운로드 및 변환'''
action_copyurl_description = '''미디어 URL을 클립보드로 복사합니다.'''
action_copyurl_title = '''URL 복사'''
action_deletehit_description = '''현재 목록에서 개체를 제거합니다.'''
action_deletehit_title = '''제거'''
action_details_description = '''이 개체에 대한 상세 정보를 표시합니다.'''
action_details_title = '''상세 정보'''
action_download_description = '''하드 디스크에 파일을 다운로드합니다.'''
action_download_title = '''다운로드'''
action_downloadconvert_description = '''미디어를 다운로드하고 다른 포맷으로 변환합니다.'''
action_downloadconvert_title = '''다운로드 및 변환'''
action_openlocalcontainer_description = '''로컬 파일 디렉토리 열기'''
action_openlocalcontainer_title = '''디렉토리 열기'''
action_openlocalfile_description = '''로컬 미디어 파일을 엽니다.'''
action_openlocalfile_title = '''미디어 열기'''
action_pin_description = '''이 개체를 핀 목록에 추가합니다.'''
action_pin_title = '''핀'''
action_quickdownload_description = '''위치를 묻지 않고 빠르게 다운로드합니다.'''
action_quickdownload_title = '''빠른 다운로드'''
action_stop_description = '''캡처 중단'''
action_stop_title = '''중단'''
adaptative = '''적응 $1'''
add_to_blacklist = '''차단 목록에 추가'''
add_to_blacklist_help = '''선택된 도메인에서 제공하는 비디오는 무시됩니다.'''
advanced = '''고급 모드'''
aggregating = '''모으는 중...'''
analyze_page = '''페이지 분석'''
appDesc = '''Download Videos from the Web'''
appName = '''Video DownloadHelper'''
appearance = '''외형'''
audio_only = '''오디오'''
behavior = '''동작'''
blacklist = '''차단 목록'''
blacklist_add_domain = '''블랙리스트 도메인 추가'''
blacklist_add_placeholder = '''블랙리스트에 올릴 도메인'''
blacklist_edit_descr = '''블랙리스트는 몇몇 도메인 내 미디어를 무시할 수 있도록 합니다.'''
blacklist_empty = '''블랙리스트에 포함된 도메인 없음'''
browser_info = '''브라우저 $1 $2 $3'''
browser_locale = '''브라우저 언어: $1'''
build_options = '''빌드 옵션: $1'''
built_on = '''$1에 빌드됨'''
bulk_in_progress = '''비디오 다운로드헬퍼의 벌크 작업이 진행중입니다. 이 탭을 닫지 마세요. 작업이 자동적으로 이뤄집니다.'''
bulk_n_videos = '''동영상 $1개'''
cancel = '''취소'''
change = '''변경사항'''
chrome_basic_mode = '''크롬 베이직 '''
chrome_inapp_descr_premium_lifetime = '''무기한 프리미엄 상태'''
chrome_inapp_descr_premium_monthly = '''월간 구독 프리미엄 상태'''
chrome_inapp_descr_premium_yearly = '''연간 구독 프리미엄 상태'''
chrome_inapp_no_subs = '''참고: Google의 Chrome 결제 서비스 지원 중단에 따라 더 이상 구독을 사용할 수 없습니다.'''
chrome_inapp_not_avail = '''사용이 불가능합니다'''
chrome_inapp_premium_lifetime = '''평생 프리미엄'''
chrome_inapp_premium_monthly = '''월간 프리미엄 구독'''
chrome_inapp_premium_yearly = '''연간 프리미엄 구독'''
chrome_install_firefox = '''파이어폭스 설치'''
chrome_install_fx_vdh = '''파이어폭스용 비디오 다운로드헬퍼'''
chrome_license_webstore_accepted = '''크롬 웹스토어로부터 라이센스 활성화'''
chrome_licensing = '''크롬 라이선스'''
chrome_noyt_text = '''불행하게도, 크롬 웹 스토어는 유튜브 동영상'''
chrome_noyt_text2 = '''파이어폭스 버전 Video DownloadHelper를 사용하면 유튜브 동영상을 다운로드 할 수 있습니다.'''
chrome_noyt_text3 = '''크롬 웹 스토어가 유튜브 비디오 다운로드를 지원하는 확장기능을 허용하지 않아, 우리는 크롬 확장기능에 이 기능을 포함할 수 없습니다.'''
chrome_premium_audio = '''소리 전용 파일은 프리미엄 모드에서만 가능합니다'''
chrome_premium_check_error = '''프리미엄 상태 확인 오류'''
chrome_premium_hls = '''프리미엄 상태가 없으면 HLS 다운로드는 이전 다운로드 후 $1분 후에만 수행할 수 있습니다.'''
chrome_premium_mode = '''크롬 프리미엄'''
chrome_premium_need_sign = '''프리미엄 기능을 사용하기 위해 크롬에 로그인해야 합니다.'''
chrome_premium_not_signed = '''크롬에 로그인되지 않음'''
chrome_premium_recheck = '''프리미엄 상태 재확인'''
chrome_premium_required = '''프리미엄 상태 필요함'''
chrome_premium_source = '''귀하는 $1 를 통한 사용자입니다.'''
chrome_product_intro = '''다음 선택사항을 통해 프리미엄으로 업그레이드하실 수 있습니다.'''
chrome_req_review = '''또는 Chrome WebStore에 멋진 리뷰를 작성해 주시겠습니까?'''
chrome_signing_in = '''크롬 로그인'''
chrome_verif_premium = '''프리미엄 상태 확인 중…'''
chrome_verif_premium_error = '''인앱 결제 API를 사용할 수 없음'''
chrome_warning_yt = '''크롬 확장기능 및 유튜브 경고'''
clear = '''비우기'''
clear_hits = '''개체 지우기'''
clear_logs = '''로그 비우기'''
coapp = '''도우미 앱'''
coapp_found = '''도우미 앱을 찾았음:'''
coapp_install = '''도우미 앱 설치'''
coapp_installed = '''도우미 앱이 설치됨'''
coapp_latest_version = '''사용 가능한 최신 버전은 $1'''
coapp_path = '''도우미 앱 바이너리:'''
coapp_recheck = '''재확인'''
coapp_required = '''도우미 응용프록그램이 필요함'''
coapp_shell = '''도우미 앱 쉘'''
coapp_unchecked = '''도우미 앰 검증중...'''
coapp_update = '''도우미 앱 업데이트'''
collecting = '''수집 중…'''
confirmation_required = '''확인 필요'''
congratulations = '''축하합니다!'''
continue = '''계속'''
convconf_2passes = '''2-패스'''
convconf_ac = '''오디오 채널'''
convconf_acnone = '''없음'''
convconf_acodec = '''오디오 코덱'''
convconf_aspect = '''화면 비율'''
convconf_audiobitrate = '''오디오 비트레이트'''
convconf_audiofreq = '''오디오 주파수'''
convconf_audioonly = '''오디오 전용'''
convconf_bitrate = '''비트레이트'''
convconf_container = '''포맷'''
convconf_duplicate = '''복제'''
convconf_ext = '''출력 파일 확장자'''
convconf_extra = '''추가 매개 변수'''
convconf_level = '''레벨'''
convconf_mono = '''모노'''
convconf_new = '''신규'''
convconf_preset = '''프리셋'''
convconf_profilev = '''비디오 프로필'''
convconf_rate = '''프레임 레이트'''
convconf_readonly = '''기본 설정이 읽기 전용입니다. 복제한 후 수정해주세요.'''
convconf_remove = '''제거'''
convconf_reset = '''모두 초기화'''
convconf_reset_confirm = '''모든 커스텀 설정들을 제거하게 됩니다.'''
convconf_save = '''저장'''
convconf_size = '''프레임 사이즈'''
convconf_stereo = '''스테레오'''
convconf_target = '''대상'''
convconf_tune = '''튠'''
convconf_vcodec = '''비디오 코덱'''
convconf_videobitrate = '''비디오 비트레이트'''
conversion_outputs = '''변환 출력'''
convert = '''변환'''
convert_local_files = '''로컬 파일 변환'''
converter_needed_aggregate = '''이 작업은 비디오 및 오디오 스트림을 집계하기 위해 시스템에 변환기가 설치되어 있어야합니다.'''
converter_needed_aggregate_why = '''왜 변환기가 필요한가요 ?'''
converter_needs_reg = '''등록 필요'''
converter_reg_audio = '''명시한 사항 혹은 자동 변환 규칙에 의한 오디오 전용 미디어 파일의 생성을 요청하였습니다. 이 기능은 등록된 변환기가 필요합니다.'''
converting = '''변환 중...'''
convrule_convert = '''변환'''
convrule_domain = '''도메인'''
convrule_extension = '''확장 기능'''
convrule_no_convert = '''변환하지 마십시오'''
convrule_output_format = '''출력 형식'''
convrules_add_rule = '''새 변환 규칙 만들기'''
convrules_edit_descr = '''변환 규칙을 통해 다운로드 직후 미디어 변환을 자동으로 수행할 수 있습니다.'''
convrules_empty = '''변환 규칙 없음'''
copy_of = '''$1 개 복사'''
corrupted_media_file = ''''$2' 파일의 '$1' 미디어에서 정보를 가져올 수 없습니다. 파일이 손상되었을 수 있습니다.'''
create = '''생성'''
custom_output = '''커스텀 출력 포맷'''
default = '''기본값'''
details_parenthesis = '''(상세 정보)'''
dev_build = '''개발 빌드'''
directory_not_exist = '''존재하지 않는 폴더'''
directory_not_exist_body = ''''$1' 폴더가 존재하지 않습니다. 생성할까요?'''
dlconv_download_and_convert = '''다운로드 및 변환'''
dlconv_output_details = '''출력 상세 정보 구성'''
donate = '''기부'''
donate_vdh = '''Video DownloadHelper 도움말'''
download_error = '''다운로드 오류'''
download_method = '''다운로드 방법'''
download_method_not_again = '''다음번에이 이 방법을 기본으로 사용'''
download_modes1 = '''실제 다운로드는 브라우저 또는 컴패니언 앱을 사용하여 수행할 수 있습니다.'''
download_modes2 = '''기술적인 이유로 브라우저 서비스에서 다운로드하면 비디오를 호스팅하는 서버에서 다운로드가 거부될 수 있으며 대체 기본 다운로드 폴더를 정의할 수 없습니다.'''
download_with_browser = '''브라우저 사용'''
download_with_coapp = '''도우미 앱 사용'''
downloading = '''다운로드 중...'''
edge_req_review = '''또는 Microsoft Edge 확장 저장소에 대한 멋진 리뷰를 작성해 주시겠습니까?'''
error = '''오류'''
error_not_directory = ''''$1'이(가) 존재하지만 디렉토리가 아닙니다.'''
errors = '''에러'''
exit_natmsgsh = '''도우미 앱 종료'''
explain_qr1 = '''결과 비디오 코너 부분에 워터마크가 있는 것을 볼 수 있습니다.'''
explain_qr2 = '''이것은 변환 기능이 등록되어 있지 않기 때문입니다.'''
failed_aggregating = '''"$1" 를 모으는 데 실패했습니다.'''
failed_converting = '''"$1" 를 변환하는 데 실패했습니다.'''
failed_getting_info = '''"$1" 에서 정보를 얻는 데 실패했습니다.'''
file_dialog_name = '''이름'''
file_generated = '''파일 "$1" 가 생성되었습니다.'''
file_ready = '''"$1" 가 준비되었습니다.'''
from_domain = '''$1 로부터'''
gallery = '''갤러리'''
gallery_files_types = '''$1 파일'''
gallery_from_domain = '''$1 의 갤러리'''
gallery_links_from_domain = '''$1 의 링크'''
general = '''일반'''
get_conversion_license = '''변환 라이센스 얻기'''
hit_details = '''개체 상세 정보'''
homepage = '''홈페이지'''
import = '''불러오기'''
in_current_tab = '''현재 탭'''
in_other_tab = '''다른 탭'''
license_key = '''라이센스 키'''
logs = '''로그'''
media = '''미디어'''
more = '''더 보기...'''
no_media_current_tab = '''현재 탭에 미디어가 없습니다'''
no_media_to_process = '''진행할 미디어가 없음'''
no_media_to_process_descr = '''파일을 감지하기 위해 비디오의 플레이 버튼을 클릭하세요'''
not_again_3months = '''3 개월 동안 다시 귀찮게 하지 마십시오.'''
not_see_again = '''이 메세지를 다시 보지 않습니다.'''
number_type = '''$1 $2'''
orphan = '''실종 개체'''
pinned = '''핀 됨'''
quality_medium = '''중간'''
quality_small = '''낮음'''
queued = '''대기 중...'''
register_converter = '''변환기 등록'''
register_existing_license = '''이미 구매한 라이센스 등록'''
registered_email = '''이메일'''
registered_key = '''키'''
req_donate = '''개발을 지원하고 조그만한 것이라도 기부하길 원하십니까?'''
req_review = '''다른 방법으로, 모질라 부가기능 웹사이트에서 좋은 리뷰를 쓰는 것은 어떨까요?'''
req_review_link = '''Video DownloadHelper 리뷰 작성'''
reset_settings = '''설정 초기화'''
running = '''실행 중'''
save = '''저장'''
select_files_to_convert = '''로컬 파일 변환'''
settings = '''설정'''
smartname_create_rule = '''규칙 만들기'''
smartname_update_rule = '''규칙 업데이트'''
smartnamer_domain = '''도메인'''
variants_list_adp = '''적응형 변종'''
weh_prefs_description_autoPin = '''다운로드 후 개체를 핀합니다.'''
weh_prefs_description_blacklistEnabled = '''일부 사이트에서 미디어를 인식하는 것을 방지합니다.'''
weh_prefs_description_coappDownloads = '''다운로드를 수행할 프로그램 선택'''
weh_prefs_description_converterAggregTuneH264 = '''강제 H264 집합 튜닝'''
weh_prefs_description_downloadControlledMax = '''일부 대역폭을 유지하기 위해 애드온에서 진행되는 다운로드 대역폭을 제어합니다.'''
weh_prefs_description_mediaweightMinSize = '''최소 크기 이하의 개체는 무시됩니다.'''
weh_prefs_description_mediaweightThreshold = '''강제적으로 해당 크기 이상의 미디어를 감지합니다.'''
weh_prefs_description_networkFilterOut = '''일반 표현식이 일부 미디어 URL들을 무시하게 합니다.'''
weh_prefs_description_noPrivateNotification = '''개인 개체 알림이 없음'''
weh_prefs_description_notifyReady = '''진행되면 알리기'''
weh_prefs_description_orphanExpiration = '''실종 개체가 제거되기 까지의 시간(초)입니다.'''
weh_prefs_description_qualitiesMaxVariants = '''같은 변종 비디오의 최대 표시 갯수를 지정합니다.'''
weh_prefs_iconActivation_option_anytab = '''모든 탭의 개체'''
weh_prefs_iconActivation_option_currenttab = '''현재 탭의 개체'''
weh_prefs_iconBadge_option_activetab = '''활성화 탭의 미디어'''
weh_prefs_iconBadge_option_anytab = '''모든 탭의 미디어'''
weh_prefs_iconBadge_option_mixed = '''혼합됨'''
weh_prefs_iconBadge_option_none = '''없음'''
weh_prefs_iconBadge_option_pinned = '''핀 된 개체'''
weh_prefs_iconBadge_option_tasks = '''실행중인 작업'''
weh_prefs_label_autoPin = '''자동 핀'''
weh_prefs_label_blacklistEnabled = '''차단 목록 활성화'''
weh_prefs_label_coappDownloads = '''다운로드 수행'''
weh_prefs_label_converterThreads = '''변환 쓰레드'''
weh_prefs_label_downloadControlledMax = '''최대 동시 다운로드'''
weh_prefs_label_iconActivation = '''아이콘 활성화'''
weh_prefs_label_iconBadge = '''아이콘 뱃지'''
weh_prefs_label_ignoreProtectedVariants = '''보호된 변형 개체 무시'''
weh_prefs_label_mediaExtensions = '''확장자 감지'''
weh_prefs_label_medialinkMinImgSize = '''최소 이미지 사이즈'''
weh_prefs_label_medialinkScanImages = '''내장 이미지 감지'''
weh_prefs_label_medialinkScanLinks = '''미디어 링크 감지'''
weh_prefs_label_mediaweightMinSize = '''최소 크기'''
weh_prefs_label_mediaweightThreshold = '''크기 임계 값'''
weh_prefs_label_networkFilterOut = '''네트워크 필터 아웃'''
weh_prefs_label_networkProbe = '''네트워크 조사'''
weh_prefs_label_notifyReady = '''알림'''
weh_prefs_label_orphanExpiration = '''실종 개체 만료 시간'''
weh_prefs_label_qualitiesMaxVariants = '''최대 변종 비디오'''
weh_prefs_label_toolsMenuEnabled = '''툴 메뉴'''
weh_prefs_smartnamerFnameSpaces_option_remove = '''삭제'''
yes = '''네'''
## V9 Strings
v9_yes = '''네'''
v9_error = '''오류'''
v9_no_media_current_tab = '''현재 탭에 미디어가 없습니다'''
v9_no_media_to_process_descr = '''파일을 감지하기 위해 비디오의 플레이 버튼을 클릭하세요'''
v9_coapp_required = '''도우미 응용프록그램이 필요함'''
v9_coapp_installed = '''도우미 앱이 설치됨'''
v9_coapp_recheck = '''재확인'''
v9_converter_needs_reg = '''등록 필요'''
v9_get_conversion_license = '''변환 라이센스 얻기'''
v9_converter_reg_audio = '''명시한 사항 혹은 자동 변환 규칙에 의한 오디오 전용 미디어 파일의 생성을 요청하였습니다. 이 기능은 등록된 변환기가 필요합니다.'''
v9_chrome_premium_required = '''프리미엄 상태 필요함'''
v9_chrome_premium_hls = '''프리미엄 상태가 없으면 HLS 다운로드는 이전 다운로드 후 $1분 후에만 수행할 수 있습니다.'''
v9_chrome_warning_yt = '''크롬 확장기능 및 유튜브 경고'''
v9_chrome_noyt_text3 = '''크롬 웹 스토어가 유튜브 비디오 다운로드를 지원하는 확장기능을 허용하지 않아, 우리는 크롬 확장기능에 이 기능을 포함할 수 없습니다.'''
v9_chrome_noyt_text2 = '''파이어폭스 버전 Video DownloadHelper를 사용하면 유튜브 동영상을 다운로드 할 수 있습니다.'''
v9_about_qr = '''파일 생성됨'''
v9_explain_qr1 = '''결과 비디오 코너 부분에 워터마크가 있는 것을 볼 수 있습니다.'''
v9_not_see_again = '''이 메세지를 다시 보지 않습니다.'''
v9_settings = '''설정'''
v9_coapp_unchecked = '''도우미 앰 검증중...'''
v9_coapp_update = '''도우미 앱 업데이트'''
v9_coapp_install = '''도우미 앱 설치'''
v9_weh_prefs_label_downloadControlledMax = '''최대 동시 다운로드'''
v9_file_ready = '''"$1" 가 준비되었습니다.'''
