Bytes = '''Bytes'''
GB = '''GB'''
KB = '''KB'''
MB = '''MB'''
about = '''Om'''
about_alpha_extra7_fx = '''På grunn av interne tekniske endringer i Firefox, måtte tillegget skrives helt om. Det kan ta noen uker før du får tilbake alle funksjonene fra tidligere versjoner.'''
about_alpha_intro = '''Dette er en alfaversjon'''
about_beta_intro = '''Dette er en betaversjon.'''
about_chrome_licenses = '''Om Chrome-lisenser'''
about_qr = '''Fil generert'''
about_vdh = '''Om Video DownloadHelper'''
action_abort_description = '''Avbryt gjeldende operasjon'''
action_abort_title = '''Avbryt'''
action_as_default = '''Utfør denne handlingen som standard'''
action_avplay_description = '''Spill av videoen med konvertererens opprinnelige viewer'''
action_avplay_title = '''Spill av'''
action_blacklist_description = '''Videoer som stammer/kommer fra valgt(e) domener vil ignoreres'''
action_blacklist_title = '''Svartelist'''
action_bulkdownload_description = '''Last ned valgte videoer'''
action_bulkdownload_title = '''Bulk nedlasting'''
action_bulkdownloadconvert_description = '''Bulk nedlasting og konverter utvalgte videoer'''
action_bulkdownloadconvert_title = '''Bulk nedlasting og konverter'''
action_copyurl_description = '''Kopier mediets adresse til utklippstavle'''
action_copyurl_title = '''Kopier URL'''
action_deletehit_description = '''Slett treff fra gjeldende liste'''
action_deletehit_title = '''Slett'''
action_details_title = '''Detaljer'''
action_download_description = '''Last ned filen til harddisk'''
action_download_title = '''Last ned'''
action_downloadconvert_description = '''Last ned mediet og konverter til et annet format'''
action_downloadconvert_title = '''Last ned og konverter'''
action_openlocalcontainer_description = '''Åpne lokal filkatalog'''
action_openlocalcontainer_title = '''Åpne katalogen'''
action_openlocalfile_description = '''Åpne lokal mediefil'''
action_openlocalfile_title = '''Åpne media'''
action_pin_title = '''Fest'''
action_quickdownload_description = '''Last ned uten å spørre etter målmappe'''
action_quickdownload_title = '''Rask nedlasting'''
action_stop_title = '''Stopp'''
adaptative = '''Adaptive $1'''
add_to_blacklist = '''Svartelist'''
add_to_blacklist_help = '''Videoer som stammer/kommer fra valgt(e) domener vil ignoreres'''
advanced = '''Avansert'''
aggregating = '''Aggregerer'''
analyze_page = '''Analyser siden.'''
appDesc = '''Last ned videoer fra Internett'''
appName = '''Video DownloadHelper'''
appearance = '''Utseende'''
audio_only = '''Kun audio'''
behavior = '''Oppførsel'''
blacklist = '''Svarteliste'''
browser_info = '''Nettleser $1 $2 $3'''
cancel = '''Avbryt'''
change = '''Endre'''
chrome_basic_mode = '''Chrome Basic (oppgradering anbefales)'''
chrome_inapp_descr_premium_lifetime = '''Premium-status uten tidsbegrensning'''
chrome_inapp_descr_premium_monthly = '''Premium-status fra et månedlig abonnement'''
chrome_inapp_descr_premium_yearly = '''Premium-status fra et årlig abonnement'''
chrome_inapp_not_avail = '''Ikke tilgjengelig'''
chrome_inapp_premium_lifetime = '''Lifetime Premium'''
chrome_inapp_premium_monthly = '''Månedlig Premium-abonnement'''
chrome_inapp_premium_yearly = '''Årlig Premium-abonnement'''
chrome_install_firefox = '''Installer Firefox'''
chrome_install_fx_vdh = '''Video DownloadHelper for Firefox'''
chrome_license_webstore_accepted = '''Aktiv lisens fra Chrome Webstore'''
chrome_licensing = '''Chrome-lisensiering'''
chrome_noyt_text = '''Dessverre tillater ikke Chrome Web Store utvidelser som laster ned videoer fra YouTube, så vi ble nødt til å fjerne denne funksjonen.'''
chrome_noyt_text2 = '''Du kan bruke Video DownloadHelper for å laste ned YouTube videoer på Firefox-versjonen.'''
chrome_premium_audio = '''Generering av kun lydfiler er bare tilgjengelig i Premium-modus'''
chrome_premium_check_error = '''Feil ved sjekk av Premium-status'''
chrome_premium_mode = '''Chrome Premium'''
chrome_premium_not_signed = '''Ikke logget inn på Chrome'''
chrome_premium_recheck = '''Sjekk Premium-status på nytt'''
chrome_premium_required = '''Premium-status kreves'''
chrome_premium_source = '''Du er en premium-bruker via $1'''
chrome_product_intro = '''Du kan oppgradere til Premium ved å bruke et av alternativene nedenfor:'''
chrome_req_review = '''Alternativt, vil du skrive en hyggelig anmeldelse på Chrome WebStore?'''
chrome_signing_in = '''Logger inn på Chrome'''
chrome_verif_premium = '''Bekrefter premiumstatus ...'''
chrome_warning_yt = '''Advarsel om Chrome utvidelser og YouTube'''
clear_hits = '''Tøm treff'''
clear_logs = '''Tøm logger'''
congratulations = '''Gratulerer!'''
continue = '''Fortsett'''
convconf_2passes = '''2 pasninger'''
convconf_ac = '''Audiokanaler'''
convconf_acnone = '''Ingen'''
convconf_acodec = '''Audiokodek'''
convconf_aspect = '''Størrelsesforhold'''
convconf_audiobitrate = '''Audio bitrate'''
convconf_audiofreq = '''Audiofrekvens'''
convconf_audioonly = '''Bare lyd'''
convconf_bitrate = '''Bitrate'''
convconf_container = '''Format'''
convconf_duplicate = '''Duplikat'''
convconf_ext = '''Filtype for resultat'''
convconf_extra = '''Ekstra parameter'''
convconf_level = '''Nivå'''
convconf_mono = '''Mono'''
convconf_new = '''Ny'''
convconf_preset = '''Forhåndsinnstilling'''
convconf_profilev = '''Videoprofil'''
convconf_rate = '''Bildefrekvens'''
convconf_readonly = '''Denne standardkonfigurasjonen er skrivebeskyttet. Dupliker for å gjøre endringer.'''
convconf_remove = '''Fjern'''
convconf_reset = '''Nullstill alt'''
convconf_reset_confirm = '''Dette vil fjerne alle tilpassede konfigurasjoner.'''
convconf_save = '''Lagre'''
convconf_size = '''Bildestørrelse'''
convconf_stereo = '''Stereo'''
convconf_target = '''Mål'''
convconf_tune = '''Juster'''
convconf_vcodec = '''Videokodek'''
convconf_videobitrate = '''Video bitrate'''
conversion_outputs = '''Konverteringsresultat'''
convert = '''Konverter'''
convert_local_files = '''Konverter lokale filer'''
converter_needed_aggregate = '''Denne operasjonen krever en konverter installert på din maskin for å aggregere video- og audiostrømmene.'''
converter_needed_aggregate_why = '''Hvorfor trenger jeg en konverter?'''
converter_needs_reg = '''Registrering nødvendig'''
converter_reg_audio = '''Du har forespurt, enten eksplisitt eller fra en automatisk konverteringsregel, om generering av en mediefil med bare lyd. Dette krever en registrert konverter.'''
converting = '''Konverterer...'''
convrule_convert = '''Konverter'''
convrule_domain = '''Domene'''
convrule_extension = '''Utvidelse'''
copy_of = '''Kopi av $1'''
custom_output = '''Tilpasset filformat'''
details_parenthesis = '''(Detaljer)'''
dlconv_download_and_convert = '''Last ned og konverter'''
dlconv_output_details = '''Konfigurer detaljer'''
donate = '''Doner'''
donate_vdh = '''Hjelp Video DownloadHelper'''
downloading = '''Laster ned...'''
errors = '''Feil'''
explain_qr1 = '''Du vil legge merke til at videoen vil inneholde et vannmerke i hjørnet.'''
explain_qr2 = '''Dette er fordi du valgte en ADP-variant, og konverteringsfunksjonen har ikke blitt registrert.'''
failed_aggregating = '''Feil ved samling av "$1"'''
failed_converting = '''Feilet konvertering "$1"'''
failed_getting_info = '''Kunne ikke hente info fra "$1"'''
file_dialog_name = '''Navn'''
file_generated = '''Filen "$1" har blitt generert.'''
file_ready = '''"$1" er nå klar'''
finalizing = '''Fullfører...'''
from_domain = '''Fra'''
gallery = '''Galleri'''
gallery_files_types = '''$1 filer'''
gallery_from_domain = '''Galleri fra $1'''
gallery_links_from_domain = '''Lenker fra $1'''
general = '''Generelt'''
get_conversion_license = '''Skaff en konverteringslisens'''
hit_details = '''Treff-detaljer'''
hit_go_to_tab = '''Gå til fane'''
in_current_tab = '''I nåværende fane'''
in_other_tab = '''Fra andre faner'''
license_key = '''Lisensnøkkel'''
logs = '''Logger'''
media = '''Media'''
more = '''Mer...'''
no_media_current_tab = '''Ingen media å behandle i nåværende fane'''
no_media_to_process = '''Ingen media å behandle'''
no_media_to_process_descr = '''Spill av video for å hjelpe å oppdage filer...'''
not_again_3months = '''Ikke plag meg med dette igjen før om 3 måneder'''
not_see_again = '''Ikke vis denne meldingen igjen'''
pinned = '''Festet'''
quality_medium = '''Middels'''
quality_small = '''Lav'''
queued = '''I kø...'''
register_converter = '''Registrer konverter'''
register_existing_license = '''Registrer en eksisterende lisens'''
registered_email = '''E-post'''
registered_key = '''Nøkkel'''
req_donate = '''Kunne du tenke deg å støtte utviklingen og donere litt?'''
req_review = '''Alternativt, kunne du tenkt deg å skrive en hyggelig anmeldelse på Mozilla sin utvidelsesside?'''
req_review_link = '''Skriv en anmeldelse om Video DownloadHelper'''
running = '''Kjører'''
save = '''Lagre'''
select_files_to_convert = '''Konverter lokale filer'''
settings = '''Innstillinger'''
smartnamer_domain = '''Domene'''
smartnamer_get_name_from_header_url = '''Finn navn fra dokument header/URL'''
smartnamer_get_name_from_page_content = '''Finn navn fra sideinnhold'''
smartnamer_get_name_from_page_title = '''Finn navn fra sidetittel'''
smartnamer_get_obfuscated_name = '''Bruk obfuskert navn'''
smartnamer_regexp = '''Ordinært uttrykk'''
smartnamer_selected_text = '''Valgt tekst'''
smartnamer_xpath_expr = '''XPath uttrykk'''
supported_sites = '''Støttede sider'''
tell_me_more = '''Fortell meg mer'''
title = '''Video DownloadHelper'''
validate_license = '''Registrer lisens'''
variants_list_adp = '''Adaptive varianter'''
variants_list_full = '''Varianter'''
vdh_notification = '''Video DownloadHelper'''
version = '''Version'''
video_only = '''Kun video'''
video_qualities = '''Videoegenskaper'''
weh_prefs_description_adpHide = '''Ikke vis ADP-varianter i nedlastingslisten'''
weh_prefs_description_converterAggregTuneH264 = '''Tving H264-justering i aggregering'''
weh_prefs_description_dashHideM4s = '''Ikke vis .m4s treff i nedlastingslisten'''
weh_prefs_description_downloadRetries = '''Antall nedlastingsforsøk'''
weh_prefs_description_hlsDownloadAsM2ts = '''Last ned HLS-strømmer som M2TS'''
weh_prefs_description_mediaweightMinSize = '''Ignorer treff under denne størrelsen'''
weh_prefs_description_mpegtsHideTs = '''Ikke vis .ts treff i nedlastingslisten'''
weh_prefs_description_notifyReady = '''Gi beskjed ved fullføring'''
weh_prefs_iconActivation_option_anytab = '''Treff fra alle faner'''
weh_prefs_iconActivation_option_currenttab = '''Treff i nåværende fane'''
weh_prefs_iconBadge_option_activetab = '''Media fra aktiv fane'''
weh_prefs_iconBadge_option_anytab = '''Media fra alle faner'''
weh_prefs_iconBadge_option_mixed = '''Blandet'''
weh_prefs_iconBadge_option_none = '''Ingen'''
weh_prefs_iconBadge_option_pinned = '''Festede treff'''
weh_prefs_iconBadge_option_tasks = '''Kjørende oppgaver'''
weh_prefs_label_avplayEnabled = '''Avpiller aktivert'''
weh_prefs_label_blacklistEnabled = '''Aktiver svarteliste'''
weh_prefs_label_chunksConcurrentDownloads = '''Antall fildeler som blir lastet ned samtidig'''
weh_prefs_label_converterThreads = '''Konverteringstråder'''
weh_prefs_label_dashEnabled = '''DASH aktivert'''
weh_prefs_label_downloadControlledMax = '''Maks. samtidige nedlastinger'''
weh_prefs_label_hlsEnabled = '''HLS aktivert'''
weh_prefs_label_ignoreProtectedVariants = '''Ignorer beskyttede varianter'''
weh_prefs_label_mediaExtensions = '''Detekter utvidelser'''
weh_prefs_label_medialinkMinImgSize = '''Minste bildestørrelse'''
weh_prefs_label_medialinkScanImages = '''Detekter innebygde bilder'''
weh_prefs_label_medialinkScanLinks = '''Detekter lenker til media'''
weh_prefs_label_mediaweightMinSize = '''Minimum størrelse'''
weh_prefs_label_networkProbe = '''Nettverksovervåking'''
weh_prefs_label_noPrivateNotification = '''Private varsler'''
weh_prefs_label_notifyReady = '''Varsling'''
weh_prefs_label_qualitiesMaxVariants = '''Maks varianter'''
weh_prefs_label_smartnamerFnameMaxlen = '''Maks lengde på filnavn'''
weh_prefs_label_tbsnEnabled = '''Facebook-støtte'''
weh_prefs_label_toolsMenuEnabled = '''Verktøy-menyen'''
weh_prefs_smartnamerFnameSpaces_option_hyphen = '''Erstatt med bindestrek'''
weh_prefs_smartnamerFnameSpaces_option_keep = '''Behold'''
weh_prefs_smartnamerFnameSpaces_option_remove = '''Fjern'''
weh_prefs_smartnamerFnameSpaces_option_underscore = '''Erstatt med understrek'''
yes = '''Ja'''
you_downloaded_n_videos = '''Du har nettopp lastet ned din $1th vellykkede fil med Video DownloadHelper.'''
