Bytes = '''$1 Octeți'''
KB = '''$1 KO'''
MB = '''$1 MO'''
about = '''Despre'''
about_qr = '''Fișier generat'''
about_vdh = '''Despre Video DownloadHelper'''
action_abort_description = '''Renunță la acțiunea în desfășurare'''
action_abort_title = '''Renunță'''
action_as_default = '''Folosește această acțiune ca implicită'''
action_blacklist_description = '''Fișierele video originale din sau servite de domeniile selectate vor fi ignorate'''
action_blacklist_title = '''Adaugă la lista neagră'''
action_copyurl_description = '''Copiază URL-ul media în clipboard'''
action_copyurl_title = '''Copiază URL-ul'''
action_deletehit_description = '''Șterge sursele găsite din lista curentă'''
action_deletehit_title = '''Șterge'''
action_details_description = '''Afișează detalii despre sursele găsite'''
action_details_title = '''Detalii'''
action_download_description = '''Descărcați fișierul pe discul dvs.'''
action_download_title = '''Descarcă'''
action_downloadconvert_description = '''Descarcă media și convertește la alt format'''
action_downloadconvert_title = '''Descarcă și convertește'''
action_openlocalfile_description = '''Deschide fișierul media local'''
action_openlocalfile_title = '''Deschide media'''
action_pin_title = '''Fixează'''
action_quickdownload_description = '''Descarcă fără să întrebe despre destinație'''
action_quickdownload_title = '''Descărcare rapidă'''
adaptative = '''Adaptiv $1'''
add_to_blacklist = '''Adaugă la lista neagră'''
add_to_blacklist_help = '''Fișierele video originale din sau servite de domeniile selectate vor fi ignorate'''
advanced = '''Avansat'''
aggregating = '''Se agreghează...'''
analyze_page = '''Analizează pagina'''
appDesc = '''Download Videos from the Web'''
appName = '''Video DownloadHelper'''
appearance = '''Aspect'''
audio_only = '''Doar audio'''
behavior = '''Comportament'''
blacklist = '''Lista neagră'''
cancel = '''Anulare'''
clear_hits = '''Curăță hit-urile'''
congratulations = '''Felicitări!'''
continue = '''Continuă'''
convconf_2passes = '''2 treceri'''
convconf_ac = '''Canale audio'''
convconf_acnone = '''Nimic'''
convconf_acodec = '''Codec audio'''
convconf_aspect = '''Raport de aspect'''
convconf_audiobitrate = '''Bitrate audio'''
convconf_audiofreq = '''Frecvența audio'''
convconf_audioonly = '''Doar audio'''
convconf_bitrate = '''Bitrate'''
convconf_container = '''Format'''
convconf_duplicate = '''Duplicat'''
convconf_ext = '''Extensia fișierului de ieșire'''
convconf_extra = '''Parametrii suplimentari'''
convconf_level = '''Nivel'''
convconf_mono = '''Mono'''
convconf_new = '''Nou'''
convconf_preset = '''Presetat'''
convconf_profilev = '''Profil video'''
convconf_rate = '''Rata cadrelor'''
convconf_readonly = '''Această configurație implicită poate fi doar citită. Duplicați-o ca să faceți modificări.'''
convconf_remove = '''Elimină'''
convconf_reset = '''Resetează tot'''
convconf_reset_confirm = '''Aceasta va elimina toate configurările personalizate'''
convconf_save = '''Salvează'''
convconf_size = '''Mărimea cadrului'''
convconf_stereo = '''Stereo'''
convconf_target = '''Țintă'''
convconf_tune = '''Reglează'''
convconf_vcodec = '''Codec video'''
convconf_videobitrate = '''Bitrate video'''
conversion_outputs = '''Ieșirea conversiei'''
convert = '''Convertește'''
convert_local_files = '''Convertește fișierele locale'''
converter_needed_aggregate = '''Această operațiune are nevoie de un convertor instalat pe sistemul dvs., pentru a agrega stream-urile video și audio.'''
converter_needed_aggregate_why = '''De ce am nevoie de convertor?'''
converter_needs_reg = '''Este necesară înregistrarea'''
converter_reg_audio = '''Ați solicitat, explicit sau printr-o regulă de conversie automată, generarea unui fișier media numai cu audio. Aceasta necesită un convertor înregistrat.'''
converting = '''Se convertește...'''
convrule_convert = '''Convertește'''
convrule_domain = '''Domeniu'''
convrule_extension = '''Extensie'''
copy_of = '''Copie a $1'''
custom_output = '''Format de ieșire personalizat'''
details_parenthesis = '''(Detalii)'''
dlconv_download_and_convert = '''Descarcă și convertește'''
dlconv_output_details = '''Configurează detaliile ieșirii'''
donate = '''Donează'''
donate_vdh = '''Help Video DownloadHelper'''
downloading = '''Se descarcă...'''
errors = '''Erori'''
explain_qr1 = '''Veți observa că video-ul rezultat conține un filigran în colț.'''
explain_qr2 = '''Aceasta se întâmplă pentru că ați ales o variantă ADP și facilitatea de conversie nu a fost înregistrată.'''
failed_aggregating = '''A eșuat agregarea "$1"'''
failed_converting = '''A eșuat conversia "$1"'''
failed_getting_info = '''A eșuat obținerea informațiilor de la "$1"'''
file_dialog_name = '''Nume'''
file_generated = '''Fișierul "$1" a fost generat.'''
file_ready = '''"$1" este gata'''
finalizing = '''Se finalizează...'''
from_domain = '''De la $1'''
gallery = '''Galerie'''
gallery_files_types = '''$1 fișiere'''
gallery_from_domain = '''Galerie de la  $1'''
gallery_links_from_domain = '''Legături de la $1'''
general = '''General'''
get_conversion_license = '''Obține o licență pentru conversie'''
hit_details = '''Detalii despre sursa identificată'''
in_current_tab = '''In fila curentă'''
in_other_tab = '''In alte file'''
license_key = '''Cheia licenței'''
logs = '''Jurnale'''
media = '''Media'''
more = '''Mai multe ...'''
no_media_current_tab = '''Nu există media de procesat în fila curentă'''
no_media_to_process = '''Nu există media de procesat'''
no_media_to_process_descr = '''Apasă redare pe video pentru a ajuta detectarea fișierelor ...'''
not_again_3months = '''Nu mă mai deranjați cu asta în urmatoarele 3 luni'''
not_see_again = '''Nu mai vedeți din nou acest mesaj'''
number_type = '''$1 $2'''
orphan = '''Orfan'''
pinned = '''Fixat'''
quality_medium = '''Mediu'''
quality_small = '''Scăzut'''
queued = '''În așteptare...'''
register_converter = '''Înregistrează convertorul'''
register_existing_license = '''Înregistrează o licență existentă'''
registered_email = '''Email'''
registered_key = '''Cheie'''
req_donate = '''Ați lua în considerare să sprijiniți dezvoltarea și să donați cât de puțin?'''
req_review = '''Ca alternativă, ați vrea să scrieți o recenzie drăguță pe site-ul addon-urilor Mozilla?'''
req_review_link = '''Scrieți o recenzie despre Video DownloadHelper'''
running = '''Rulează'''
save = '''Salvează'''
select_files_to_convert = '''Convertește fișierele locale'''
settings = '''Setări'''
smartnamer_delay = '''Întârzie numirea captării (ms)'''
smartnamer_domain = '''Domeniu'''
smartnamer_get_name_from_header_url = '''Obține nume din antetul/URL-ul documentului'''
smartnamer_get_name_from_page_content = '''Obține numele din conținutul paginii'''
smartnamer_get_name_from_page_title = '''Obține nume din titlul paginii'''
smartnamer_get_obfuscated_name = '''Folosește nume disimulat'''
smartnamer_regexp = '''Expresie regulată'''
smartnamer_selected_text = '''Textul selectat'''
smartnamer_xpath_expr = '''Expresia XPath'''
supported_sites = '''Site-uri suportate'''
tell_me_more = '''Spune mai multe despre asta.'''
title = '''Video DownloadHelper'''
validate_license = '''Înregistrează licența'''
variants_list_adp = '''Variante adaptive'''
variants_list_full = '''Variante'''
vdh_notification = '''Video DownloadHelper'''
version = '''Versiune $1'''
video_only = '''Doar video'''
video_qualities = '''Calitate video'''
weh_prefs_description_adpHide = '''Nu arăta variante ADP în lista de descărcare'''
weh_prefs_description_converterAggregTuneH264 = '''Forțează reglarea H264 la agregare'''
weh_prefs_description_downloadRetries = '''Numărul reîncercărilor de descărcare'''
weh_prefs_description_downloadRetryDelay = '''Întârziere între reîncercările de descărcare (ms)'''
weh_prefs_description_noPrivateNotification = '''Fără notificări pentru hit-urile private'''
weh_prefs_description_notifyReady = '''Notifică când s-a procesat'''
weh_prefs_iconActivation_option_anytab = '''Surse identificate în orice filă'''
weh_prefs_iconActivation_option_currenttab = '''Surse identificate în fila curentă'''
weh_prefs_iconBadge_option_activetab = '''Media din fila activă'''
weh_prefs_iconBadge_option_anytab = '''Media din orice filă'''
weh_prefs_iconBadge_option_mixed = '''Mixat'''
weh_prefs_iconBadge_option_none = '''Nici unul'''
weh_prefs_iconBadge_option_pinned = '''Detectări fixate'''
weh_prefs_iconBadge_option_tasks = '''Activități care rulează'''
weh_prefs_label_converterThreads = '''Firele conversiei'''
weh_prefs_label_ignoreProtectedVariants = '''Ignoră variantele protejate'''
weh_prefs_label_mediaExtensions = '''Detectează extensii'''
weh_prefs_label_medialinkMinImgSize = '''Mărimea minimă a imaginii'''
weh_prefs_label_medialinkScanImages = '''Detectează imaginile încorporate'''
weh_prefs_label_medialinkScanLinks = '''Detectează legături către media'''
weh_prefs_label_networkProbe = '''Examinare rețea'''
weh_prefs_smartnamerFnameSpaces_option_hyphen = '''Înlocuiește cu cratime'''
weh_prefs_smartnamerFnameSpaces_option_keep = '''Păstrează'''
weh_prefs_smartnamerFnameSpaces_option_remove = '''Elimină'''
weh_prefs_smartnamerFnameSpaces_option_underscore = '''Înlocuiește cu linie de subliniere'''
you_downloaded_n_videos = '''Tocmai ați descărcat cu succes al $1th fișier cu Video DownloadHelper.'''
